version: '3'
services:
  redis:
    image: redis:3
  rails:
    build: .
    environment:
      RAILS_ENV: development
#    volumes:
#      - .:/app
#      - bundle:/bundle
    ports:
      - "8080:8080"
    depends_on:
      - redis
volumes:
  bundle:
    driver: local