redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production: *redis
#  channel_prefix: graphql-subscriptions-rails_production

development: *redis
#  channel_prefix: graphql-subscriptions-rails_development

test: *redis
#  channel_prefix: graphql-subscriptions-rails_test



#development:
#  adapter: async
#
#test:
#  adapter: async
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1
#  channel_prefix: graphql-subscriptions-rails_production
